name: Backup S3
version: 15.0.9
image: alexbabel/backup-s3
homeassistant: "2022.4"
slug: backup_s3
description: Sync your Home Assistant Supervisor Backups with S3
url: https://github.com/AlexanderBabel/hassio-addons
startup: once
boot: auto
init: false
arch:
  - aarch64
  - amd64
map:
  - backup:rw
options:
  awskey: My-Access-Key
  awssecret: ""
  bucketname: My-Bucket
  endpoint: ""
  checkurl: ""
  usename: true
schema:
  awskey: str
  awssecret: str
  bucketname: str
  endpoint: str?
  checkurl: str?
  usename: bool
