---
name: librespot player
version: 1.1.1
slug: librespot-player
description: Example add-on by Community Home Assistant Add-ons
url: https://github.com/AlexanderBabel/hassio-addons
init: true
host_network: true
map:
  - config:rw
  - share:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  pipe: /share/owntone/music/librespot-java
  metadatapipe: /share/owntone/music/librespot-java.metadata
schema:
  pipe: str?
  metadatapipe: str?
