---
name: Backup S3
version: 2.5.2
slug: backup-s3
description: Sync your Home Assistant Supervisor Backups with S3
url: https://github.com/AlexanderBabel/hassio-addons
startup: once
boot: auto
map:
  - backup:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  pipe: /share/owntone/music/librespot-java
  metadatapipe: /share/owntone/music/librespot-java.metadata
  awskey: My-Access-Key
  awssecret: ""
  bucketname: My-Bucket
  endpoint: ""
  checkurl: ""
  usename: true
schema:
  awskey: str
  awssecret: str
  bucketname: str
  endpoint: str?
  checkurl: str?
  usename: bool
